package Domain.models.entities.Usuario;

public enum TipoPermiso {
    DISTRIBUCIONVIANDAS,
    DONACIONMONETARIA,
    DONACIONVIANDAS,
    REGISTROPERSONAVULNERABLE,
    OFRECERPRODUCTOS,
    ENCARGARSEHELADERA,
    CARGACSV,
    VISUALIZARALERTAS,
    VISUALIZARREPORTES,
    VISUALIZARHELADERAS,
    GESTIONARFORMULARIOS,
    GESTIONARUSUARIOS,
    REGISTROVISITATECNICA,
    REGISTRARTECNICO,
    VISUALIZARVISITASTECNICAS
}
